//
// TESTING API ROUTES
//

POST http://localhost:9000/users
Content-Type: application/json

{
	"username" : "Jasa",
	"password" : "jasa123",
	"email" : "jasa.opresnik@gmail.com",
    "token" : "false"
}

###

PUT http://localhost:9000/users/login
Content-Type: application/json

{
	"email" : "jasa.opresnik@gmail.com",
	"password" : "jasa123"
}

###

PUT http://localhost:9000/users/logout
Content-Type: application/json

###

GET http://localhost:9000/users
Content-Type: application/json

###

GET http://localhost:9000/users/6530232102a7005cea4fdefc
Content-Type: application/json

###

GET http://localhost:9000/users/current
Content-Type: application/json

###

PUT http://localhost:9000/users/6530232102a7005cea4fdefc
Content-Type: application/json

{
	"password" : "jasa12345"
}

###

DELETE http://localhost:9000/users/6530232102a7005cea4fdefc
Content-Type: application/json

###
###
###

POST http://localhost:9000/groups
Content-Type: application/json

{
	"name" : "friends",
	"users" : "6530232102a7005cea4fdefc",
	"transactions" : 0
}

###

GET http://localhost:9000/groups
Content-Type: application/json

###

GET http://localhost:9000/groups/654243ae94025bb5d485c7d4
Content-Type: application/json

###

PUT http://localhost:9000/groups/654243ae94025bb5d485c7d4
Content-Type: application/json

{
	"transactions": 2
}

###

DELETE http://localhost:9000/groups/6530257ab4142f375201c4a0
Content-Type: application/json

###

POST http://localhost:9000/purchases
Content-Type: application/json


{
	"name": "food",
	"cost": 10.99,
	"user": "6532bd1b505cc8a8395fc3e9"
}