//
// TESTING API ROUTES
//

POST http://localhost:9000/users
Content-Type: application/json

{
	"username" : "Jasa",
	"password" : "jasa123",
	"email" : "jasa.opresnik@gmail.com",
    "token" : "false"
}

###

PUT http://localhost:9000/users/login
Content-Type: application/json

{
	"email" : "jasa.opresnik@gmail.com",
	"password" : "jasa123"
}

###

PUT http://localhost:9000/users/logout
Content-Type: application/json

###

GET http://localhost:9000/users
Content-Type: application/json

###

GET http://localhost:9000/users/6530419a1c5a8f19b3784658
Content-Type: application/json

###

GET http://localhost:9000/users/current
Content-Type: application/json

###

PUT http://localhost:9000/users/6532c0e1044a9646b50779ee
Content-Type: application/json

{
	"balance" : "10"
}

###

DELETE http://localhost:9000/users/6530232102a7005cea4fdefc
Content-Type: application/json

###
###
###

POST http://localhost:9000/groups
Content-Type: application/json

{
	"name" : "friends",
	"users" : "6530232102a7005cea4fdefc",
	"transactions" : 0
}

###

GET http://localhost:9000/groups
Content-Type: application/json

###

GET http://localhost:9000/groups/654243ae94025bb5d485c7d4
Content-Type: application/json

###

PUT http://localhost:9000/groups/654801d87c7e7f8e305c876c
Content-Type: application/json

{
	"purchases": "654802ab7c7e7f8e305c879f"
}

###

PUT http://localhost:9000/groups/65550586ed7d6f4a0b28b2b0/remove/65493279911d4fb619bf72c8
Content-Type: application/json

###

GET http://localhost:9000/groups/657457a35486e7ef70e120c9/hasUser/6532c0e1044a9646b50779ee
Content-Type: application/json

###

PUT http://localhost:9000/groups/6570cc5e5f43cc32058ee6cf
Content-Type: application/json

{
	"users": "65555b641812a2b491c35d1b"
}

###

DELETE http://localhost:9000/groups/6530257ab4142f375201c4a0
Content-Type: application/json

###

GET http://localhost:9000/purchases
Content-Type: application/json

###

GET http://localhost:9000/purchases/6548f2c61b1d9daa064bd10d
Content-Type: application/json

###

POST http://localhost:9000/purchases
Content-Type: application/json

{
	"name": "food",
	"cost": 10.99,
	"user": "6532c0e1044a9646b50779ee",
	"group": "657457a35486e7ef70e120c9"
}

###

GET http://localhost:9000/purchases/user/65555b641812a2b491c35d1b
Content-Type: application/json

###

DELETE http://localhost:9000/purchases/6577257c3af9fec2481318b5
Content-Type: application/json