//
// TESTING API ROUTES
//

POST http://localhost:9000/users
Content-Type: application/json

{
	"username" : "Jasa",
	"password" : "jasa123",
	"email" : "jasa.opresnik@gmail.com",
    "token" : ""
}

###

GET http://localhost:9000/users
Content-Type: application/json

###

GET http://localhost:9000/users/6530232102a7005cea4fdefc
Content-Type: application/json

###

PUT http://localhost:9000/users/6530232102a7005cea4fdefc
Content-Type: application/json

{
	"password" : "jasa12345"
}

###

DELETE http://localhost:9000/users/6530232102a7005cea4fdefc
Content-Type: application/json

###
###
###

POST http://localhost:9000/groups
Content-Type: application/json

{
	"name" : "friends",
	"users" : "6530232102a7005cea4fdefc",
	"transactions" : 0
}

###

GET http://localhost:9000/groups
Content-Type: application/json

###

GET http://localhost:9000/groups/6530238b02a7005cea4fdf0a
Content-Type: application/json

###

PUT http://localhost:9000/groups/6530238b02a7005cea4fdf0a
Content-Type: application/json

{
	"transactions": 2
}

###

DELETE http://localhost:9000/groups/6530257ab4142f375201c4a0
Content-Type: application/json